source 'https://api.berkshelf.com'

cookbook 'apt-periodic'
cookbook 'chef-solo-search'
cookbook 'curl'
cookbook 'dokku', github: 'fgrehm/chef-dokku'
cookbook 'dokku-simple', github: 'rlister/chef-dokku-simple'
cookbook 'fail2ban'
cookbook 'firewall'
cookbook 'logrotate'
cookbook 'openssh'
cookbook 'openssl'
cookbook 'resolver'