source 'https://api.berkshelf.com'

cookbook 'apt-periodic'
cookbook 'chef-solo-search'
cookbook 'curl'
cookbook 'fail2ban'
cookbook 'firewall'
cookbook 'git'
cookbook 'logrotate'
cookbook 'openssh'
cookbook 'openssl'
cookbook 'resolver'
cookbook 'swap'